exclude: ^LICENSE/|\.(html|csv|svg|md)$
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/john-hen/Flake8-pyproject
    rev: 1.0.1
    hooks:
    -   id: Flake8-pyproject