on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

name: MySQL Check 
jobs:
  my_sql_check:
    name: ${{ matrix.python_version }} MySQL check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10"]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install featuretools-sql with optional, dev, and test requirements
        run: |
          pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
      - name: Set up MySQL databases 
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE dummy;' -uroot -proot
      - name: Run tests
        run: | 
          pytest tests/* 