
# This is not actually testing anything at the moment

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

name: MySQL Check
jobs:
  my_sql_check:
    name: ${{ matrix.python_version }} MySQL check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python_version: ["3.10"]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install requirements
        run: python -m pip install .
      - name: Display processes
        run: |
          echo | ps xa | grep mysqld
      - name: run tests
        run: |
          mysql -h 127.0.0.1 --port 8888 -u root -p password -e "CREATE DATABASE db;"
          echo "Got here!"
