# Testing how to get postgres running in CI
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

name: Test postgres instance
jobs:
  postgres-test:
    # Containers have to run on Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python_version: [ "3.10" ]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # health checks -- borrowed from connectorX
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install featuretools_sql with optional, dev, and test requirements
        run: |
          pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
      - name: Seed the database
        run: psql $POSTGRES_URL -f scripts/postgres.sql
        env:
          POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
      - name: Run test
        run: pytest featuretools_sql/tests/unit_tests/test_postgres_query.py
